"""
Base Code Generator

Abstract base class for platform-specific code generators.
"""

from abc import ABC, abstractmethod
from typing import Dict, Any, List

from ..models.schemas import DSLLayer, PlatformConfig


class BaseCodeGenerator(ABC):
    """Abstract base class for code generators."""

    def __init__(self, dsl: DSLLayer, config: PlatformConfig):
        self.dsl = dsl
        self.config = config
        self.platform_name = self._get_platform_name()
        self.mode = config.target.get('mode', 'batch')

    @abstractmethod
    def _get_platform_name(self) -> str:
        """Return platform name (spark, flink, etc.)."""
        pass

    @abstractmethod
    def generate_source_ddl(self) -> str:
        """Generate DDL for source tables/connectors."""
        pass

    @abstractmethod
    def generate_sink_ddl(self) -> str:
        """Generate DDL for sink tables/connectors."""
        pass

    @abstractmethod
    def generate_transformations(self) -> str:
        """Generate transformation logic (views, queries)."""
        pass

    @abstractmethod
    def generate_udf_registrations(self) -> str:
        """Generate UDF/UDTF registration code."""
        pass

    def generate_full_script(self) -> str:
        """Generate complete executable script."""
        parts = [
            self._generate_header(),
            self.generate_udf_registrations(),
            self.generate_source_ddl(),
            self.generate_sink_ddl(),
            self.generate_transformations(),
            self._generate_footer()
        ]
        return '\n\n'.join(part for part in parts if part)

    def _generate_header(self) -> str:
        """Generate script header with imports and setup."""
        return f"-- Generated by Platform Compiler for {self.platform_name.upper()}\n-- Mode: {self.mode}"

    def _generate_footer(self) -> str:
        """Generate script footer."""
        return "-- End of generated script"

    def _resolve_connector_config(self, table_name: str, connector_type: str) -> Dict[str, Any]:
        """Resolve connector configuration from platform config."""
        connectors = self.config.connectors.get(f'{connector_type}s', [])
        for conn in connectors:
            if conn.get('name') == table_name:
                return conn.get('config', {})
        return {}

    def _format_type(self, sql_type: str) -> str:
        """Convert SQL type to platform-specific type."""
        type_mapping = {
            'STRING': 'STRING',
            'INT': 'INT',
            'BIGINT': 'BIGINT',
            'DOUBLE': 'DOUBLE',
            'FLOAT': 'FLOAT',
            'BOOLEAN': 'BOOLEAN',
            'TIMESTAMP': 'TIMESTAMP',
            'DATE': 'DATE',
        }
        # Handle complex types
        if sql_type.startswith('ARRAY<'):
            inner = sql_type[6:-1]
            return f'ARRAY<{self._format_type(inner)}>'
        elif sql_type.startswith('MAP<'):
            inner = sql_type[4:-1]
            parts = inner.split(',', 1)
            if len(parts) == 2:
                return f'MAP<{self._format_type(parts[0].strip())}, {self._format_type(parts[1].strip())}>'
        elif sql_type.startswith('STRUCT<'):
            inner = sql_type[7:-1]
            return f'STRUCT<{inner}>'  # Simplified
        
        return type_mapping.get(sql_type.upper(), 'STRING')
