%%% @doc
%%% Base Code Generator module.
%%% Abstract base for platform-specific code generators.
%%% @end

-module(base_generator).

-export([init/2, generate_full_script/2, format_type/1]).
-export_behaviour(gen_server).

-include("schemas.hrl").

%%====================================================================
%% Type definitions
%%====================================================================

-type generator_state() :: #{
    dsl => dsl_layer(),
    config => platform_config(),
    platform_name => string(),
    mode => string()
}.

%%====================================================================
%% API functions
%%====================================================================

%% @doc Initialize a generator with DSL and config.
-spec init(dsl_layer(), platform_config()) -> generator_state().
init(DSL, Config) ->
    PlatformName = get_platform_name(Config),
    Mode = maps:get(<<"mode">>, maps:get(target, Config, #{}), <<"batch">>),
    #{
        dsl => DSL,
        config => Config,
        platform_name => binary_to_list(PlatformName),
        mode => binary_to_list(Mode)
    }.

%% @doc Generate complete executable script.
-spec generate_full_script(generator_state(), module()) -> string().
generate_full_script(State, GeneratorModule) ->
    Header = generate_header(State),
    UDFs = GeneratorModule:generate_udf_registrations(State),
    Sources = GeneratorModule:generate_source_ddl(State),
    Sinks = GeneratorModule:generate_sink_ddl(State),
    Transformations = GeneratorModule:generate_transformations(State),
    Footer = generate_footer(State),
    
    string:join([P || P <- [Header, UDFs, Sources, Sinks, Transformations, Footer], P =/= ""], "\n\n").

%% @doc Convert SQL type to platform-specific type.
-spec format_type(string()) -> string().
format_type(SqlType) ->
    TypeMapping = #{
        <<"STRING">> => <<"STRING">>,
        <<"INT">> => <<"INT">>,
        <<"BIGINT">> => <<"BIGINT">>,
        <<"DOUBLE">> => <<"DOUBLE">>,
        <<"FLOAT">> => <<"FLOAT">>,
        <<"BOOLEAN">> => <<"BOOLEAN">>,
        <<"TIMESTAMP">> => <<"TIMESTAMP">>,
        <<"DATE">> => <<"DATE">>
    },
    
    UpperType = string:to_upper(SqlType),
    
    %% Handle complex types
    case re:run(UpperType, "^ARRAY<(.+)>$", [{capture, all_but_first, list}]) of
        {match, [Inner]} ->
            "ARRAY<" ++ format_type(string:trim(Inner)) ++ ">";
        nomatch ->
            case re:run(UpperType, "^MAP<(.+),(.+)>$", [{capture, all_but_first, list}]) of
                {match, [K, V]} ->
                    "MAP<" ++ format_type(string:trim(K)) ++ ", " ++ format_type(string:trim(V)) ++ ">";
                nomatch ->
                    case re:run(UpperType, "^STRUCT<(.+)>$", [{capture, all_but_first, list}]) of
                        {match, [_Inner]} ->
                            "STRUCT<" ++ string:trim(re:replace(UpperType, "^STRUCT<|>$", "", [{return, list}])) ++ ">";
                        nomatch ->
                            binary_to_list(maps:get(list_to_binary(UpperType), TypeMapping, <<"STRING">>))
                    end
            end
    end.

%%====================================================================
%% Internal functions
%%====================================================================

-spec get_platform_name(platform_config()) -> binary().
get_platform_name(Config) ->
    Target = maps:get(target, Config, #{}),
    maps:get(<<"platform">>, Target, <<"spark">>).

-spec generate_header(generator_state()) -> string().
generate_header(State) ->
    PlatformName = maps:get(platform_name, State),
    Mode = maps:get(mode, State),
    "-- Generated by Platform Compiler for " ++ string:to_upper(PlatformName) ++ 
    "\n-- Mode: " ++ Mode.

-spec generate_footer(generator_state()) -> string().
generate_footer(_State) ->
    "-- End of generated script".

%% Helper to resolve connector config
-spec resolve_connector_config(string(), atom(), platform_config()) -> map().
resolve_connector_config(TableName, ConnectorType, Config) ->
    Connectors = maps:get(ConnectorType, maps:get(connectors, Config, #{}), []),
    resolve_connector_search(TableName, Connectors).

-spec resolve_connector_search(string(), [map()]) -> map().
resolve_connector_search(_Name, []) ->
    #{};
resolve_connector_search(Name, [Conn | Rest]) ->
    ConnName = maps:get(<<"name">>, Conn, <<>>),
    TargetName = list_to_binary(Name),
    case ConnName =:= TargetName of
        true ->
            maps:get(<<"config">>, Conn, #{});
        false ->
            resolve_connector_search(Name, Rest)
    end.
