%%% @doc
%%% Spark SQL Code Generator.
%%% Generates Spark SQL code for Batch and Structured Streaming modes.
%%% Includes Airflow DAG generation for orchestration.
%%% @end

-module(spark_generator).

-export([generate_source_ddl/1, generate_sink_ddl/1, generate_transformations/1,
         generate_udf_registrations/1, generate_airflow_dag/1]).

-include("schemas.hrl").

%%====================================================================
%% API functions
%%====================================================================

%% @doc Generate Spark source table DDL.
-spec generate_source_ddl(map()) -> string().
generate_source_ddl(State) ->
    DSL = maps:get(dsl, State),
    Config = maps:get(config, State),
    Sources = maps:get(sources, maps:get(connectors, Config, #{}), []),
    
    Header = "-- ==========================================\n-- SOURCE TABLES\n-- ==========================================",
    TablesDDL = [generate_source_table(T, Sources, State) || T <- maps:get(tables, DSL, [])],
    string:join([Header | TablesDDL], "\n\n").

%% @doc Generate Spark sink table DDL.
-spec generate_sink_ddl(map()) -> string().
generate_sink_ddl(State) ->
    Config = maps:get(config, State),
    Sinks = maps:get(sinks, maps:get(connectors, Config, #{}), []),
    
    Header = "-- ==========================================\n-- SINK TABLES\n-- ==========================================",
    SinksDDL = [generate_sink_table(S, State) || S <- Sinks],
    string:join([Header | SinksDDL], "\n\n").

%% @doc Generate transformation logic (views and queries).
-spec generate_transformations(map()) -> string().
generate_transformations(State) ->
    DSL = maps:get(dsl, State),
    
    Header = "-- ==========================================\n-- TRANSFORMATIONS\n-- ==========================================",
    ViewsDDL = [generate_view(Name, Query, State) || {Name, Query} <- maps:to_list(maps:get(views, DSL, #{}))],
    InsertsDDL = [translate_to_spark(I) ++ ";" || I <- maps:get(inserts, DSL, [])],
    string:join([Header | ViewsDDL ++ InsertsDDL], "\n\n").

%% @doc Generate UDF registration code for Spark.
-spec generate_udf_registrations(map()) -> string().
generate_udf_registrations(State) ->
    DSL = maps:get(dsl, State),
    
    Header = "-- ==========================================\n-- UDF/UDTF REGISTRATIONS\n-- ==========================================",
    ModelsDDL = [generate_model_registration(M) || M <- maps:get(models, DSL, [])],
    Footer = "-- Window function helpers are built-in to Spark SQL",
    string:join([Header | ModelsDDL ++ [Footer]], "\n\n").

%% @doc Generate Airflow DAG Python code for Spark job.
-spec generate_airflow_dag(map()) -> string().
generate_airflow_dag(State) ->
    Config = maps:get(config, State),
    Meta = maps:get(meta, Config, #{}),
    Orch = maps:get(orchestration, Config, #{}),
    Airflow = maps:get(airflow, Orch, undefined),
    Exec = maps:get(execution, Config, #{}),
    Memory = maps:get(memory, Exec, #{}),
    
    DagId = re:replace(maps:get(<<"name">>, Meta, <<"spark_pipeline">>), "-", "_", [global, {return, list}]),
    Owner = binary_to_list(maps:get(<<"owner">>, Meta, <<"data-engineering">>)),
    Desc = binary_to_list(maps:get(<<"description">>, Meta, <<"Spark pipeline">>)),
    Version = binary_to_list(maps:get(<<"version">>, Meta, <<"1.0.0">>)),
    
    ScheduleInterval = case Airflow of
        undefined -> "@daily";
        _ -> binary_to_list(maps:get(<<"schedule_interval">>, Airflow, <<"@daily">>))
    end,
    
    StartDate = case Airflow of
        undefined -> "2024-01-01";
        _ -> binary_to_list(maps:get(<<"start_date">>, Airflow, <<"2024-01-01">>))
    end,
    
    Catchup = case Airflow of
        undefined -> false;
        _ -> maps:get(<<"catchup">>, Airflow, false)
    end,
    
    Retries = case Airflow of
        undefined -> 2;
        _ -> maps:get(<<"retries">>, Airflow, 2)
    end,
    
    Parallelism = maps:get(parallelism, Exec, 1),
    ExecutorMemory = binary_to_list(maps:get(<<"executor">>, Memory, <<"4g">>)),
    DriverMemory = binary_to_list(maps:get(<<"driver">>, Memory, <<"2g">>)),
    
    ShufflePartitions = integer_to_list(Parallelism * 2),
    
    io_lib:format(
"\"\"\"
Airflow DAG for ~s
Generated by Platform Compiler
\"\"\"

from airflow import DAG
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
from datetime import datetime, timedelta

default_args = {
    'owner': '~s',
    'depends_on_past': False,
    'email_on_failure': True,
    'email_on_retry': False,
    'retries': ~B,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    '~s',
    default_args=default_args,
    description='~s',
    schedule_interval='~s',
    start_date=datetime(~s),
    catchup=~s,
    tags=['spark', 'sql', '~s'],
)

submit_spark_job = SparkSubmitOperator(
    task_id='run_spark_sql',
    application='hdfs:///scripts/generated/~s.sql',
    conf={
        'spark.sql.shuffle.partitions': '~s',
        'spark.executor.memory': '~s',
        'spark.driver.memory': '~s',
    },
    verbose=True,
    dag=dag,
)",
        [DagId, Owner, Retries, DagId, Desc, ScheduleInterval, 
         re:replace(StartDate, "-", ", ", [global, {return, list}]),
         atom_to_list(Catchup), Version, DagId, ShufflePartitions, 
         ExecutorMemory, DriverMemory]).

%%====================================================================
%% Internal functions
%%====================================================================

-spec generate_source_table(map(), [map()], map()) -> string().
generate_source_table(Table, Sources, State) ->
    Name = maps:get(name, Table),
    Connector = find_connector(Name, Sources),
    
    case Connector of
        undefined ->
            create_temp_view(Table);
        _ ->
            ConnType = binary_to_list(maps:get(<<"type">>, Connector, <<"hdfs">>)),
            ConnConfig = maps:get(<<"config">>, Connector, #{}),
            case ConnType of
                "kafka" -> generate_kafka_source(Table, ConnConfig, State);
                "hdfs" -> generate_file_source(Table, ConnConfig, State);
                "s3" -> generate_file_source(Table, ConnConfig, State);
                _ -> "-- Unsupported source type: " ++ ConnType
            end
    end.

-spec generate_sink_table(map(), map()) -> string().
generate_sink_table(Sink, State) ->
    Name = binary_to_list(maps:get(<<"name">>, Sink, <<"">>)),
    ConnType = binary_to_list(maps:get(<<"type">>, Sink, <<"hdfs">>)),
    ConnConfig = maps:get(<<"config">>, Sink, #{}),
    
    case ConnType of
        "kafka" -> generate_kafka_sink(Name, ConnConfig);
        "hdfs" -> generate_file_sink(Name, ConnConfig);
        "s3" -> generate_file_sink(Name, ConnConfig);
        _ -> "-- Unsupported sink type: " ++ ConnType
    end.

-spec generate_kafka_source(map(), map(), map()) -> string().
generate_kafka_source(Table, Config, State) ->
    Name = maps:get(name, Table),
    Columns = string:join([K ++ " " ++ base_generator:format_type(V) || {K, V} <- maps:to_list(maps:get(columns, Table, #{}))], ", "),
    Servers = string:join(binary_to_list(maps:get(<<"bootstrap_servers">>, Config, [<<"localhost:9092">>])), ","),
    Topic = binary_to_list(maps:get(<<"topic">>, Config, list_to_binary(Name))),
    Format = binary_to_list(maps:get(<<"format">>, Config, <<"json">>)),
    
    Mode = maps:get(mode, State, "batch"),
    
    case Mode of
        "streaming" ->
            Watermark = case maps:get(stream_config, Table, undefined) of
                undefined -> "";
                SC -> 
                    TimeAttr = maps:get(time_attribute, SC, ""),
                    WmInterval = maps:get(watermark, SC, "10 seconds"),
                    ".withWatermark(\"" ++ TimeAttr ++ "\", \"" ++ WmInterval ++ "\")"
            end,
            io_lib:format(
"-- Kafka Source: ~s
CREATE OR REPLACE TEMPORARY VIEW ~s
USING kafka
OPTIONS (
  kafka.bootstrap.servers \"~s\",
  subscribe \"~s\",
  startingOffsets \"latest\",
  failOnDataLoss \"false\"
);

-- Parse Kafka payload
SELECT FROM_JSON(CAST(value AS STRING), \"~s\") AS data
FROM ~s_raw~s;", [Name, Name, Servers, Topic, Columns, Name, Watermark]);
        _ ->
            io_lib:format(
"-- Kafka Source (Batch): ~s
-- Note: Batch mode reads all available data from Kafka
CREATE OR REPLACE TEMPORARY VIEW ~s
USING kafka
OPTIONS (
  kafka.bootstrap.servers \"~s\",
  subscribe \"~s\",
  startingOffsets \"earliest\"
);", [Name, Name, Servers, Topic])
    end.

-spec generate_file_source(map(), map(), map()) -> string().
generate_file_source(Table, Config, _State) ->
    Name = maps:get(name, Table),
    DefaultPath = list_to_binary("/data/" ++ atom_to_list(Name)),
    Path = binary_to_list(maps:get(<<"path">>, Config, DefaultPath)),
    Format = binary_to_list(maps:get(<<"format">>, Config, <<"parquet">>)),
    PartitionBy = maps:get(<<"partition_by">>, Config, []),
    
    PartitionClause = case PartitionBy of
        [] -> "";
        _ -> "\nPARTITIONED BY (" ++ string:join([binary_to_list(P) || P <- PartitionBy], ", ") ++ ")"
    end,
    
    io_lib:format(
"-- File Source: ~s
CREATE OR REPLACE TEMPORARY VIEW ~s
USING ~s
OPTIONS (
  path \"~s\"
)~s;", [Name, Name, Format, Path, PartitionClause]).

-spec generate_kafka_sink(string(), map()) -> string().
generate_kafka_sink(Name, Config) ->
    Servers = string:join(binary_to_list(maps:get(<<"bootstrap_servers">>, Config, [<<"localhost:9092">>])), ","),
    Topic = binary_to_list(maps:get(<<"topic">>, Config, list_to_binary(Name))),
    
    io_lib:format(
"-- Kafka Sink: ~s
-- Write to Kafka using:
-- df.write
--   .format(\"kafka\")
--   .option(\"kafka.bootstrap.servers\", \"~s\")
--   .option(\"topic\", \"~s\")
--   .save()", [Name, Servers, Topic]).

-spec generate_file_sink(string(), map()) -> string().
generate_file_sink(Name, Config) ->
    DefaultPath = list_to_binary("/data/" ++ Name),
    Path = binary_to_list(maps:get(<<"path">>, Config, DefaultPath)),
    Format = binary_to_list(maps:get(<<"format">>, Config, <<"parquet">>)),
    PartitionBy = maps:get(<<"partition_by">>, Config, []),
    Overwrite = maps:get(<<"overwrite">>, Config, false),
    
    Mode = case Overwrite of
        true -> "overwrite";
        false -> "append"
    end,
    
    PartitionClause = case PartitionBy of
        [] -> "";
        _ -> "\n-- .partitionBy(" ++ string:join([binary_to_list(P) || P <- PartitionBy], ", ") ++ ")"
    end,
    
    io_lib:format(
"-- File Sink: ~s
-- Write using:
-- df.write
--   .mode(\"~s\")
--   .format(\"~s\")~s
-- .option(\"path\", \"~s\")
-- .save()", [Name, Mode, Format, PartitionClause, Path]).

-spec create_temp_view(map()) -> string().
create_temp_view(Table) ->
    Name = maps:get(name, Table),
    Cols = string:join(["CAST(NULL AS " ++ base_generator:format_type(T) ++ ") AS " ++ K || {K, T} <- maps:to_list(maps:get(columns, Table, #{}))], ", "),
    io_lib:format("CREATE OR REPLACE TEMPORARY VIEW ~s AS SELECT ~s;", [Name, Cols]).

-spec generate_model_registration(map()) -> string().
generate_model_registration(Model) ->
    Name = maps:get(name, Model),
    Path = maps:get(path, Model),
    InputSchema = maps:get(input_schema, Model),
    OutputSchema = maps:get(output_schema, Model),
    
    io_lib:format(
"-- Model: ~s
-- Path: ~s
-- Input: ~s, Output: ~s
-- spark.udf.register('~s', apply_model('~s'), ~s)", 
        [Name, Path, InputSchema, OutputSchema, Name, Path, OutputSchema]).

-spec generate_view(string(), string(), map()) -> string().
generate_view(Name, Query, _State) ->
    TranslatedQuery = translate_to_spark(Query),
    io_lib:format("CREATE OR REPLACE TEMPORARY VIEW ~s AS\n~s;", [Name, TranslatedQuery]).

-spec translate_to_spark(string()) -> string().
translate_to_spark(Query) ->
    Translations = [
        {"TUMBLE_START(", "window.start, "},
        {"TUMBLE_END(", "window.end, "},
        {"TUMBLE(", "window("},
        {"HOP(", "window("},
        {"SESSION(", "session_window("},
        {"APPLY_MODEL(", "apply_model("},
        {"ENCODE_TEXT(", "encode_text("},
        {"LLM_GENERATE(", "llm_generate("}
    ],
    lists:foldl(fun({From, To}, Acc) -> re:replace(Acc, From, To, [global, {return, list}]) end, Query, Translations).

-spec find_connector(string(), [map()]) -> map() | undefined.
find_connector(_Name, []) ->
    undefined;
find_connector(Name, [C | Rest]) ->
    BinName = maps:get(<<"name">>, C, <<>>),
    case BinName =:= list_to_binary(Name) of
        true -> C;
        false -> find_connector(Name, Rest)
    end.
