-- Generated by Platform Compiler for FLINK
-- Mode: streaming

-- ==========================================

-- UDF/UDTF REGISTRATIONS

-- ==========================================

-- Model: fraud_detector

-- Path: hdfs:///models/fraud_detector_v2.pkl

-- Input: STRUCT, Output: FLOAT


-- Create Python UDF for fraud_detector
-- CREATE TEMPORARY FUNCTION fraud_detector 
-- AS 'udfs.fraud_detector_udf' 
-- LANGUAGE PYTHON;


-- Model: user_embedder

-- Path: hdfs:///models/user_encoder.onnx

-- Input: transaction_history, Output: ARRAY


-- Create Python UDF for user_embedder
-- CREATE TEMPORARY FUNCTION user_embedder 
-- AS 'udfs.user_embedder_udf' 
-- LANGUAGE PYTHON;


-- ==========================================

-- SOURCE TABLES

-- ==========================================

-- Kafka Source: raw_events
CREATE TABLE raw_events (
  event_id STRING,
  user_id STRING,
  transaction_amount DOUBLE,
  merchant_id STRING,
  event_time STRING,
  WATERMARK FOR event_time AS event_time - INTERVAL '10 seconds'
) WITH (
  'connector' = 'kafka',
  'properties.bootstrap.servers' = 'kafka-broker-1.prod.internal:9092,kafka-broker-2.prod.internal:9092,kafka-broker-3.prod.internal:9092',
  'topic' = 'transactions-prod',
  'scan.startup.mode' = 'latest-offset',
  'format' = 'json'
);

-- File Source: historical_transactions
CREATE TABLE historical_transactions (
  transaction_id STRING,
  user_id STRING,
  amount DOUBLE,
  category STRING,
  transaction_date DATE
) WITH (
  'connector' = 'filesystem',
  'path' = 's3://company-data/historical/transactions/',
  'format' = 'parquet'
);

-- File Source: merchant_risk
CREATE TABLE merchant_risk (
  merchant_id STRING,
  risk_score DOUBLE,
  category STRING
) WITH (
  'connector' = 'filesystem',
  'path' = 's3://company-data/static/merchant_risk/',
  'format' = 'parquet'
);

-- ==========================================

-- SINK TABLES

-- ==========================================

-- Kafka Sink: fraud_alerts
-- Use INSERT INTO to write to this sink
-- Configuration:
--   bootstrap.servers: kafka-broker-1.prod.internal:9092,kafka-broker-2.prod.internal:9092
--   topic: fraud-alerts-prod
--   semantic: exactly-once

-- File Sink: monitoring_output
-- Use INSERT INTO to write to this sink
-- Configuration:
--   path: s3://company-data/monitoring/fraud-stats/
--   format: parquet

-- ==========================================

-- TRANSFORMATIONS

-- ==========================================

CREATE VIEW enriched_transactions AS
SELECT
    t.event_id,
    t.user_id,
    t.transaction_amount,
    t.merchant_id,
    t.event_time,
    m.risk_score AS merchant_risk,
    m.category AS merchant_category
FROM raw_events t
LEFT JOIN merchant_risk m ON t.merchant_id = m.merchant_id;

CREATE VIEW fraud_predictions AS
SELECT
    e.event_id,
    e.user_id,
    e.transaction_amount,
    e.event_time,
    apply_model(fraud_detector, 
        STRUCT(e.user_id, e.transaction_amount, e.merchant_risk)
    ) AS fraud_probability
FROM enriched_transactions e;

CREATE VIEW flagged_transactions AS
SELECT
    event_id,
    user_id,
    transaction_amount,
    fraud_probability,
    event_time,
    CASE 
        WHEN fraud_probability > 0.8 THEN 'HIGH_RISK'
        WHEN fraud_probability > 0.5 THEN 'MEDIUM_RISK'
        ELSE 'LOW_RISK'
    END AS risk_level
FROM fraud_predictions;

CREATE VIEW fraud_stats_5min AS
SELECT
    TUMBLE_START(event_time, INTERVAL '5' MINUTES) AS window_start,
    TUMBLE_END(event_time, INTERVAL '5' MINUTES) AS window_end,
    COUNT(*) AS total_transactions,
    SUM(CASE WHEN fraud_probability > 0.5 THEN 1 ELSE 0 END) AS suspicious_count,
    AVG(fraud_probability) AS avg_fraud_score
FROM fraud_predictions
GROUP BY TUMBLE(event_time, INTERVAL '5' MINUTES);

INSERT INTO fraud_alerts SELECT event_id,
    user_id,
    transaction_amount,
    fraud_probability,
    risk_level,
    event_time
FROM flagged_transactions
WHERE risk_level IN ('HIGH_RISK', 'MEDIUM_RISK');

INSERT INTO monitoring_output SELECT * FROM fraud_stats_5min;

-- End of generated script