#!/bin/bash
#
# Platform Compiler - Shell Script Version
# Компилирует SQL-DSL в платформенный код (Spark/Flink)
#

set -e

# Цвета для вывода
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Глобальные переменные
DSL_FILE=""
CONFIG_FILE=""
OUTPUT_DIR=""
PLATFORM=""
MODE=""

# Логирование
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Парсинг аргументов командной строки
parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            -d|--dsl)
                DSL_FILE="$2"
                shift 2
                ;;
            -c|--config)
                CONFIG_FILE="$2"
                shift 2
                ;;
            -o|--output)
                OUTPUT_DIR="$2"
                shift 2
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                log_error "Неизвестный аргумент: $1"
                show_help
                exit 1
                ;;
        esac
    done
    
    # Валидация обязательных параметров
    if [[ -z "$DSL_FILE" || -z "$CONFIG_FILE" || -z "$OUTPUT_DIR" ]]; then
        log_error "Обязательные параметры не указаны!"
        show_help
        exit 1
    fi
}

show_help() {
    cat << EOF
Platform Compiler - Компилятор SQL-DSL в платформенный код

Использование:
  $(basename "$0") -d <dsl_file> -c <config_file> -o <output_dir>

Параметры:
  -d, --dsl      Путь к файлу SQL-DSL (pipeline.dsl)
  -c, --config   Путь к YAML конфигурации платформы
  -o, --output   Директория для выходных файлов
  -h, --help     Показать эту справку

Пример:
  $(basename "$0") -d pipeline.dsl -c platform.yaml -o output/

EOF
}

# Проверка существования файлов
check_files() {
    if [[ ! -f "$DSL_FILE" ]]; then
        log_error "DSL файл не найден: $DSL_FILE"
        exit 1
    fi
    
    if [[ ! -f "$CONFIG_FILE" ]]; then
        log_error "Файл конфигурации не найден: $CONFIG_FILE"
        exit 1
    fi
}

# Чтение значения из YAML (простой парсер)
# Usage: yaml_get "key" < file.yaml
yaml_get() {
    local key="$1"
    grep "^${key}:" | sed "s/^${key}:[[:space:]]*//" | tr -d '"' | tr -d "'"
}

# Чтение вложенного значения из YAML
# Usage: yaml_get_nested "execution" "parallelism" < file.yaml
yaml_get_nested() {
    local parent="$1"
    local key="$2"
    awk "/^${parent}:/,/^[a-z]/" | grep "^[[:space:]]*${key}:" | head -1 | sed "s/^[[:space:]]*${key}:[[:space:]]*//" | tr -d '"' | tr -d "'"
}

# Загрузка конфигурации
load_config() {
    log_info "Загрузка конфигурации: $CONFIG_FILE"
    
    # Извлекаем основные параметры
    PLATFORM=$(grep -A5 "^target:" "$CONFIG_FILE" | grep "platform:" | sed 's/.*platform:[[:space:]]*//' | tr -d '"' | tr -d "'")
    MODE=$(grep -A5 "^target:" "$CONFIG_FILE" | grep "mode:" | sed 's/.*mode:[[:space:]]*//' | tr -d '"' | tr -d "'")
    
    # Значения по умолчанию
    PLATFORM=${PLATFORM:-spark}
    MODE=${MODE:-batch}
    
    log_info "Платформа: $PLATFORM, Режим: $MODE"
}

# Парсинг DSL файла
parse_dsl() {
    log_info "Парсинг DSL: $DSL_FILE"
    
    # Удаляем комментарии и сохраняем в временный файл
    TEMP_DSL=$(mktemp)
    sed 's/--.*$//' "$DSL_FILE" | tr '\n' ' ' > "$TEMP_DSL"
    
    # Извлекаем DEFINE TABLE (с поддержкой многострочных определений)
    TABLES=()
    while IFS= read -r line; do
        if [[ -n "$line" ]]; then
            TABLES+=("$line")
        fi
    done < <(grep -oE 'DEFINE[[:space:]]+TABLE[[:space:]]+[a-zA-Z_][a-zA-Z0-9_]*[[:space:]]*\([^)]+\)' "$TEMP_DSL" 2>/dev/null || true)
    
    # Извлекаем CREATE VIEW
    VIEWS=()
    while IFS= read -r line; do
        if [[ -n "$line" ]]; then
            VIEWS+=("$line")
        fi
    done < <(grep -oE 'CREATE[[:space:]]+VIEW[[:space:]]+[a-zA-Z_][a-zA-Z0-9_]*[[:space:]]+AS[[:space:]]+[^;]+' "$TEMP_DSL" 2>/dev/null | sed 's/;$//' || true)
    
    # Извлекаем INSERT
    INSERTS=()
    while IFS= read -r line; do
        if [[ -n "$line" ]]; then
            INSERTS+=("$line")
        fi
    done < <(grep -oE 'INSERT[[:space:]]+INTO[[:space:]]+[a-zA-Z_][a-zA-Z0-9_]*[[:space:]]+SELECT[[:space:]]+[^;]+' "$TEMP_DSL" 2>/dev/null | sed 's/;$//' || true)
    
    rm -f "$TEMP_DSL"
    
    log_info "Найдено таблиц: ${#TABLES[@]}, представлений: ${#VIEWS[@]}, INSERT: ${#INSERTS[@]}"
}

# Генерация Spark SQL
generate_spark() {
    log_info "Генерация кода для Spark..."
    
    local sql_file="$OUTPUT_DIR/${PIPELINE_NAME}.sql"
    
    cat > "$sql_file" << HEADER
-- Generated by Platform Compiler for SPARK
-- Mode: $MODE
-- ==========================================

HEADER
    
    # UDF регистрации
    echo "-- ==========================================" >> "$sql_file"
    echo "-- UDF REGISTRATIONS" >> "$sql_file"
    echo "-- ==========================================" >> "$sql_file"
    echo "" >> "$sql_file"
    
    # Source DDL
    echo "-- ==========================================" >> "$sql_file"
    echo "-- SOURCE TABLES" >> "$sql_file"
    echo "-- ==========================================" >> "$sql_file"
    echo "" >> "$sql_file"
    
    for table in "${TABLES[@]}"; do
        local table_name=$(echo "$table" | grep -oP 'DEFINE\s+TABLE\s+\K\w+')
        echo "-- Table: $table_name" >> "$sql_file"
        echo "CREATE OR REPLACE TEMPORARY VIEW $table_name AS SELECT * FROM parquet.\`hdfs:///data/$table_name\`;" >> "$sql_file"
        echo "" >> "$sql_file"
    done
    
    # Sink DDL
    echo "-- ==========================================" >> "$sql_file"
    echo "-- SINK TABLES" >> "$sql_file"
    echo "-- ==========================================" >> "$sql_file"
    echo "" >> "$sql_file"
    
    # Transformations
    echo "-- ==========================================" >> "$sql_file"
    echo "-- TRANSFORMATIONS" >> "$sql_file"
    echo "-- ==========================================" >> "$sql_file"
    echo "" >> "$sql_file"
    
    for view in "${VIEWS[@]}"; do
        echo "$view;" >> "$sql_file"
        echo "" >> "$sql_file"
    done
    
    for insert in "${INSERTS[@]}"; do
        echo "$insert;" >> "$sql_file"
        echo "" >> "$sql_file"
    done
    
    echo "-- End of generated script" >> "$sql_file"
    
    log_info "Создан файл: $sql_file"
    
    # Генерация Airflow DAG если нужно
    local orch_type=$(grep -A10 "^orchestration:" "$CONFIG_FILE" | grep "type:" | head -1 | sed 's/.*type:[[:space:]]*//' | tr -d '"' | tr -d "'")
    
    if [[ "$orch_type" == "airflow" ]]; then
        generate_airflow_dag
    fi
}

# Генерация Flink SQL
generate_flink() {
    log_info "Генерация кода для Flink..."
    
    local sql_file="$OUTPUT_DIR/${PIPELINE_NAME}.sql"
    
    cat > "$sql_file" << HEADER
-- Generated by Platform Compiler for FLINK
-- Mode: $MODE
-- ==========================================

HEADER
    
    # UDF регистрации
    echo "-- ==========================================" >> "$sql_file"
    echo "-- UDF/UDTF REGISTRATIONS" >> "$sql_file"
    echo "-- ==========================================" >> "$sql_file"
    echo "" >> "$sql_file"
    
    # Source DDL
    echo "-- ==========================================" >> "$sql_file"
    echo "-- SOURCE TABLES" >> "$sql_file"
    echo "-- ==========================================" >> "$sql_file"
    echo "" >> "$sql_file"
    
    for table in "${TABLES[@]}"; do
        local table_name=$(echo "$table" | grep -oP 'DEFINE\s+TABLE\s+\K\w+')
        echo "-- Kafka Source: $table_name" >> "$sql_file"
        cat >> "$sql_file" << KAFKA_SOURCE
CREATE TABLE $table_name (
  id STRING,
  data STRING,
  ts TIMESTAMP(3),
  WATERMARK FOR ts AS ts - INTERVAL '5 seconds'
) WITH (
  'connector' = 'kafka',
  'properties.bootstrap.servers' = 'localhost:9092',
  'topic' = '$table_name',
  'scan.startup.mode' = 'latest-offset',
  'format' = 'json'
);

KAFKA_SOURCE
    done
    
    # Sink DDL
    echo "-- ==========================================" >> "$sql_file"
    echo "-- SINK TABLES" >> "$sql_file"
    echo "-- ==========================================" >> "$sql_file"
    echo "" >> "$sql_file"
    
    # Transformations
    echo "-- ==========================================" >> "$sql_file"
    echo "-- TRANSFORMATIONS" >> "$sql_file"
    echo "-- ==========================================" >> "$sql_file"
    echo "" >> "$sql_file"
    
    for view in "${VIEWS[@]}"; do
        echo "$view;" >> "$sql_file"
        echo "" >> "$sql_file"
    done
    
    for insert in "${INSERTS[@]}"; do
        echo "$insert;" >> "$sql_file"
        echo "" >> "$sql_file"
    done
    
    echo "-- End of generated script" >> "$sql_file"
    
    log_info "Создан файл: $sql_file"
    
    # Генерация Kubernetes manifest если нужно
    local orch_type=$(grep -A10 "^orchestration:" "$CONFIG_FILE" | grep "type:" | head -1 | sed 's/.*type:[[:space:]]*//' | tr -d '"' | tr -d "'")
    
    if [[ "$orch_type" == "kubernetes" ]]; then
        generate_k8s_manifest
    fi
}

# Генерация Airflow DAG
generate_airflow_dag() {
    log_info "Генерация Airflow DAG..."
    
    local dag_file="$OUTPUT_DIR/dag_${PIPELINE_NAME}.py"
    local schedule_interval=$(grep -A10 "^orchestration:" "$CONFIG_FILE" | grep "schedule_interval:" | sed 's/.*schedule_interval:[[:space:]]*//' | tr -d '"' | tr -d "'")
    schedule_interval=${schedule_interval:-@daily}
    
    cat > "$dag_file" << DAG_EOF
"""
Airflow DAG for $PIPELINE_NAME
Generated by Platform Compiler
"""

from airflow import DAG
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
from datetime import datetime, timedelta

default_args = {
    'owner': 'data-engineering',
    'depends_on_past': False,
    'email_on_failure': True,
    'email_on_retry': False,
    'retries': 2,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    '${PIPELINE_NAME}',
    default_args=default_args,
    description='Spark pipeline',
    schedule_interval='$schedule_interval',
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=['spark', 'sql'],
)

submit_spark_job = SparkSubmitOperator(
    task_id='run_spark_sql',
    application='hdfs:///scripts/generated/${PIPELINE_NAME}.sql',
    conf={
        'spark.sql.shuffle.partitions': '200',
        'spark.executor.memory': '4g',
        'spark.driver.memory': '2g',
    },
    verbose=True,
    dag=dag,
)
DAG_EOF
    
    log_info "Создан файл: $dag_file"
}

# Генерация Kubernetes manifest
generate_k8s_manifest() {
    log_info "Генерация Kubernetes manifest..."
    
    local k8s_file="$OUTPUT_DIR/deployment_${PIPELINE_NAME}.yaml"
    local namespace=$(grep -A15 "^orchestration:" "$CONFIG_FILE" | grep -A10 "kubernetes:" | grep "namespace:" | sed 's/.*namespace:[[:space:]]*//' | tr -d '"' | tr -d "'")
    namespace=${namespace:-default}
    
    local parallelism=$(grep -A5 "^execution:" "$CONFIG_FILE" | grep "parallelism:" | sed 's/.*parallelism:[[:space:]]*//' | tr -d '"' | tr -d "'")
    parallelism=${parallelism:-1}
    
    cat > "$k8s_file" << K8S_EOF
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: ${PIPELINE_NAME}
  namespace: ${namespace}
spec:
  image: flink:1.17
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "${parallelism}"
    state.backend: rocksdb
    state.checkpoints.dir: "file:///tmp/flink-checkpoints"
    execution.checkpointing.interval: "60000ms"
  serviceAccount: flink
  jobManager:
    resource:
      memory: 2048m
      cpu: 1
  taskManager:
    resource:
      memory: 4096m
      cpu: 2
  job:
    jarURI: local:///opt/flink/usrlib/${PIPELINE_NAME}.jar
    parallelism: ${parallelism}
    upgradeMode: stateless
K8S_EOF
    
    log_info "Создан файл: $k8s_file"
}

# Основная функция компиляции
compile() {
    log_info "Начало компиляции..."
    
    # Создаем директорию вывода
    mkdir -p "$OUTPUT_DIR"
    
    # Извлекаем имя пайплайна из имени DSL файла
    PIPELINE_NAME=$(basename "$DSL_FILE" .dsl)
    
    # Парсим DSL
    parse_dsl
    
    # Выбираем генератор по платформе
    case "$PLATFORM" in
        spark)
            generate_spark
            ;;
        flink)
            generate_flink
            ;;
        *)
            log_error "Неподдерживаемая платформа: $PLATFORM"
            exit 1
            ;;
    esac
    
    log_info "Компиляция завершена успешно!"
    log_info "Выходные файлы находятся в: $OUTPUT_DIR"
}

# Точка входа
main() {
    parse_args "$@"
    check_files
    load_config
    compile
}

# Запуск
main "$@"
