-- Generated by Platform Compiler for SPARK
-- Mode: batch

-- ==========================================

-- UDF/UDTF REGISTRATIONS

-- ==========================================

-- Model: fraud_detector

-- Path: hdfs:///models/fraud_detector_v2.pkl

-- Input: STRUCT, Output: FLOAT

-- spark.udf.register('fraud_detector', apply_model('hdfs:///models/fraud_detector_v2.pkl'), FLOAT)



-- Model: user_embedder

-- Path: hdfs:///models/user_encoder.onnx

-- Input: transaction_history, Output: ARRAY

-- spark.udf.register('user_embedder', apply_model('hdfs:///models/user_encoder.onnx'), ARRAY)



-- Window function helpers are built-in to Spark SQL

-- ==========================================

-- SOURCE TABLES

-- ==========================================

-- File Source: raw_events
CREATE OR REPLACE TEMPORARY VIEW raw_events
USING parquet
OPTIONS (
  path "hdfs:///data/raw_events/parquet/"
)
PARTITIONED BY (year, month, day);

-- File Source: historical_transactions
CREATE OR REPLACE TEMPORARY VIEW historical_transactions
USING parquet
OPTIONS (
  path "hdfs:///data/historical_transactions/"
);

-- File Source: merchant_risk
CREATE OR REPLACE TEMPORARY VIEW merchant_risk
USING parquet
OPTIONS (
  path "hdfs:///data/merchant_risk/"
);

-- ==========================================

-- SINK TABLES

-- ==========================================

-- File Sink: fraud_alerts
-- Write using:
-- df.write
--   .mode("overwrite")
--   .format("parquet")
-- .option("path", "hdfs:///data/fraud_alerts/output/")
-- .save()

-- File Sink: monitoring_output
-- Write using:
-- df.write
--   .mode("append")
--   .format("parquet")
-- .option("path", "hdfs:///data/monitoring/stats/")
-- .save()

-- ==========================================

-- TRANSFORMATIONS

-- ==========================================

CREATE OR REPLACE TEMPORARY VIEW enriched_transactions AS
SELECT
    t.event_id,
    t.user_id,
    t.transaction_amount,
    t.merchant_id,
    t.event_time,
    m.risk_score AS merchant_risk,
    m.category AS merchant_category
FROM raw_events t
LEFT JOIN merchant_risk m ON t.merchant_id = m.merchant_id;

CREATE OR REPLACE TEMPORARY VIEW fraud_predictions AS
SELECT
    e.event_id,
    e.user_id,
    e.transaction_amount,
    e.event_time,
    apply_model(fraud_detector, 
        STRUCT(e.user_id, e.transaction_amount, e.merchant_risk)
    ) AS fraud_probability
FROM enriched_transactions e;

CREATE OR REPLACE TEMPORARY VIEW flagged_transactions AS
SELECT
    event_id,
    user_id,
    transaction_amount,
    fraud_probability,
    event_time,
    CASE 
        WHEN fraud_probability > 0.8 THEN 'HIGH_RISK'
        WHEN fraud_probability > 0.5 THEN 'MEDIUM_RISK'
        ELSE 'LOW_RISK'
    END AS risk_level
FROM fraud_predictions;

INSERT INTO fraud_alerts SELECT event_id,
    user_id,
    transaction_amount,
    fraud_probability,
    risk_level,
    event_time
FROM flagged_transactions
WHERE risk_level IN ('HIGH_RISK', 'MEDIUM_RISK');

INSERT INTO monitoring_output SELECT * FROM fraud_stats_5min;

-- End of generated script