"""
Airflow DAG for fraud-detection-batch
Generated by Platform Compiler
"""

from airflow import DAG
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
from datetime import datetime, timedelta

default_args = {
    'owner': 'data-engineering-team',
    'depends_on_past': False,
    'email_on_failure': True,
    'email_on_retry': False,
    'retries': 2,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    'fraud_detection_batch',
    default_args=default_args,
    description='Nightly batch fraud detection pipeline',
    schedule_interval='0 2 * * *',
    start_date=datetime(2024, 01, 01),
    catchup=false,
    tags=['spark', 'sql', '1.0.0'],
)

submit_spark_job = SparkSubmitOperator(
    task_id='run_spark_sql',
    application='hdfs:///scripts/generated/fraud_detection_batch.sql',
    conf={
        'spark.sql.shuffle.partitions': '100',
        'spark.executor.memory': '16g',
        'spark.driver.memory': '8g',
    },
    verbose=True,
    dag=dag,
)
